# Generated by Django 4.2 on 2023-04-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('content_translate', models.TextField(blank=True)),
                ('is_error', models.BooleanField(default=False)),
                ('is_loading', models.BooleanField(default=False)),
                ('is_inverse', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'conversations',
                'db_table': 'conversations',
            },
        ),
    ]
