# Generated by Django 4.2 on 2023-04-20 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('members', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_conversions', to='members.members'),
        ),
        migrations.AddField(
            model_name='chat',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_chats', to='conversations.conversations'),
        ),
        migrations.AddField(
            model_name='chat',
            name='translate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.translatetypesmaster'),
        ),
    ]
