# Generated by Django 4.2 on 2023-04-20 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_error',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='is_loading',
        ),
    ]
