# Generated by Django 4.2 on 2023-04-20 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('conversations', '0003_remove_chat_is_error_remove_chat_is_loading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='translate_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.translatetypesmaster'),
        ),
    ]
