# Generated by Django 4.2 on 2023-04-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_alter_chat_translate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_inverse',
        ),
        migrations.AddField(
            model_name='chat',
            name='role',
            field=models.IntegerField(default=1),
        ),
    ]
