# Generated by Django 4.2 on 2023-04-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_limit', models.IntegerField(default=100000)),
                ('quantity_token_used', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'members',
                'db_table': 'members',
            },
        ),
    ]
