# Generated by Django 4.2 on 2023-06-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompts',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
