# Generated by Django 4.2 on 2023-06-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='content',
            field=models.CharField(max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='templates',
            name='icon',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='templates',
            name='text_feature_button',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
