# Generated by Django 4.2 on 2023-06-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_templates_content_templates_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='question_asked',
            field=models.TextField(null=True),
        ),
    ]
