# Generated by Django 4.2 on 2023-06-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documents_member_documents_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='language',
            field=models.CharField(default='Vietnamese', max_length=255),
            preserve_default=False,
        ),
    ]
